// Generated by Xata Codegen 0.29.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "userDetails",
    columns: [
      { name: "userId", type: "string", notNull: true, defaultValue: "null" },
      { name: "bio", type: "string", notNull: true, defaultValue: "null" },
      { name: "location", type: "string", notNull: true, defaultValue: "null" },
      { name: "fullName", type: "string", notNull: true, defaultValue: "null" },
      { name: "email", type: "string" },
      { name: "phone", type: "string" },
      { name: "gender", type: "string" },
      { name: "dob", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type UserDetails = InferredTypes["userDetails"];
export type UserDetailsRecord = UserDetails & XataRecord;

export type DatabaseSchema = {
  userDetails: UserDetailsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Barrack-Amuyunzu-s-workspace-bq01mc.us-east-1.xata.sh/db/mindcare",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
